version: "2"

services:
  web:
    build: ./trackhs
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - dlangimg

  redis:
    image: redis
    command: "redis-server --appendonly yes"

  dlangimg:
    build: ./dlangimg
    image: dlangimg
